name: Deploy Static Site to GKE

on:
  push:
    branches:
      - master

env:
  REGION: us-central1
  REPOSITORY: static-site-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build Docker Image
      run: |
        IMAGE_URI=$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPOSITORY/static-site:latest
        docker build -t $IMAGE_URI .

    - name: Push Docker Image
      run: |
        IMAGE_URI=$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPOSITORY/static-site:latest
        docker push $IMAGE_URI

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials static-site-cluster \
          --zone ${{ secrets.GCP_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        IMAGE_URI=$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPOSITORY/static-site:latest

        kubectl apply -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: static-site
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: static-site
          template:
            metadata:
              labels:
                app: static-site
            spec:
              containers:
              - name: static-site
                image: $IMAGE_URI
                ports:
                - containerPort: 80
        EOF

        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: Service
        metadata:
          name: static-site-service
        spec:
          type: LoadBalancer
          selector:
            app: static-site
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80
        EOF

    - name: Get External IP
      run: |
        echo "Waiting for external IP..."
        sleep 60
        kubectl get service static-site-service
